--- 
title: "Principes de la formulation des aliments pour animaux d'élevage"
author: "Zonlehoua Coulibali, Agronome, PhD."
date: "28/10/2020" #"`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Notes du cours de formulation, format gitbook."
---

# Objectifs du cours {#intro}

L’intérêt de la formulation des aliments pour animaux tient à l’adaptation permanente de leur composition à des contraintes variées et évolutives, à l’ajustement du pourcentage de chaque composante en fonction du contexte technique et des besoins des animaux. La formulation tient aussi compte de l'évolution du coût des matières premières.

Le cours est conçu avec pour objectif de guider l’apprenant dans la construction, l’acquisition des compétences nécessaires à l'exercice d'un emploi ou assumer la responsabilité de formulateur de régimes alimentaires pour animaux d’élevage au compte d’un éleveur, d’un industriel ou à titre personnel.

Avant de concocter des recttes alimentaires proprement dites, la connaissance d’un ensemble de concepts théoriques liés à la discipline est présentée de façon assez simplifiée, invitant l’apprenant à plus d’aproffondissement dans une revue bibliographique proposée. 

De façon spécifique, tout apprenant au sortir de ce cours devait être à mesure (entre autres) :

-	de se rappeler les différentes matières premières utilisables en alimentation animale et les nutriments principaux apportés à la ration (cours de bromatologie) ;

-	de connaître la physiologie de la digestion chez les monogastriques et les ruminants ;

-	d’expliquer les notions de dépenses alimentaires, de besoins alimentaires et de recommandations alimentaires pour un animal ou un troupeau donné ;

-	d’expliquer les formes d’expression des besoins des animaux et des apports de la ration ;

-	de catégoriser ces notions selon les caractéristiques de l’animal : l’espèce, son stade physiologique, le type d’élevage, le type de production attendu, … ;

-	de calculer un régime alimentaire équilibré pour animaux d’élevage ;

-	etc.

En d’autres termes, l’apprenant devrait être à mesure de comprendre les bases scientifiques de la formulation, c’est-à-dire les matières premières utilisées dans l’alimentation et la théorie des modèles de recommandations dans la conduite de l’alimention animale.

_La version du document sera régulièrement actualisée_.


**TABLE DES MATIÈRES**

[**Chapitre 1.**](https://rgoals.github.io/formulation/index.html) Objectifs du cours

[**Chapitre 2.**](https://rgoals.github.io/formulation/rappels.html) Rappels sur les aliments

[**Chapitre 3.**](https://rgoals.github.io/formulation/digestion.html) Digestion des aliments

[**Chapitre 4.**](https://rgoals.github.io/formulation/expression.html) Expression des besoins et des apports

[**Chapitre 5.**](https://rgoals.github.io/formulation/pratique.html) Pratique de la formulation

[**Références bibliographiques**](https://rgoals.github.io/formulation/references.html)
